"""DataTrace implementation for environment/walk/split figures.

Provides a lightweight, plot-oriented wrapper around environment and walk data
that implements the PlotTrace protocol.
"""

from __future__ import annotations

import math
from typing import Any

from torch_tem.data.world import World
from torch_tem.figures.core.types import PlotTrace


class DataTrace:
    """Plot-ready trace for environment and walk data.

    A lightweight wrapper that implements the PlotTrace protocol for use with
    data-oriented figures (environment layout, walk trajectories, etc.).

    Walk structure (as generated by World.generate_walks):
        Each walk is a list of steps, where each step is:
            [location_dict, observation_tensor, action_int]
        
        location_dict contains at minimum: {"id": int, "shiny": bool}

    Attributes:
        worlds: List of World objects (one per environment in batch).
        walks: List of walks (one per environment), where each walk is a list
               of [location_dict, observation_tensor, action_int] steps.
        visited: Optional list of per-environment visit tracking (list of bool lists).
        meta: Metadata dictionary (e.g., split name, batch index).
    """

    def __init__(
        self,
        worlds: list[World],
        walks: list[list[list[Any]]],
        visited: list[list[bool]] | None = None,
        meta: dict[str, Any] | None = None,
    ):
        """Initialize DataTrace.

        Args:
            worlds: List of World objects.
            walks: List of walks (same length as worlds).
            visited: Optional per-environment visit tracking.
            meta: Optional metadata dictionary.

        Raises:
            ValueError: If worlds and walks have mismatched lengths.
        """
        if len(worlds) != len(walks):
            raise ValueError(f"Worlds and walks must have same length (got {len(worlds)} vs {len(walks)})")

        self.worlds = worlds
        self.walks = walks
        self.visited = visited
        self.meta = meta or {}

    @property
    def batch_size(self) -> int:
        """Number of parallel environments in the trace."""
        return len(self.worlds)

    @property
    def n_steps(self) -> int:
        """Number of timesteps in the trace (length of first walk)."""
        if len(self.walks) == 0 or len(self.walks[0]) == 0:
            return 0
        return len(self.walks[0])

    def select_env(self, env_idx: int) -> DataTrace:
        """Extract trace for a single environment.

        Args:
            env_idx: Index of environment to extract (0 <= env_idx < batch_size).

        Returns:
            New DataTrace with batch_size=1 containing only env_idx.

        Raises:
            IndexError: If env_idx is out of bounds.
        """
        if not (0 <= env_idx < self.batch_size):
            raise IndexError(f"env_idx {env_idx} out of range [0, {self.batch_size})")

        return DataTrace(
            worlds=[self.worlds[env_idx]],
            walks=[self.walks[env_idx]],
            visited=[self.visited[env_idx]] if self.visited else None,
            meta=self.meta.copy(),
        )

    def downsample_time(self, stride: int) -> DataTrace:
        """Downsample trace along time dimension.

        Args:
            stride: Keep every stride-th timestep.

        Returns:
            New DataTrace with n_steps = ceil(original_n_steps / stride).

        Raises:
            ValueError: If stride < 1.
        """
        if stride < 1:
            raise ValueError(f"stride must be >= 1 (got {stride})")

        if stride == 1:
            # No downsampling needed
            return self

        downsampled_walks = [[walk[i] for i in range(0, len(walk), stride)] for walk in self.walks]

        return DataTrace(
            worlds=self.worlds,  # Worlds are not time-dependent
            walks=downsampled_walks,
            visited=self.visited,  # Visit tracking is cumulative, not time-sliced
            meta=self.meta.copy(),
        )


def collect_data_trace(datamodule, split: str) -> DataTrace:
    """Collect a DataTrace from a datamodule split.

    Utility function to standardize data trace collection from TEMDataModule.
    Samples a batch and assembles the corresponding DataTrace with World objects.

    Args:
        datamodule: TEMDataModule instance (must be set up).
        split: Split name ("train", "validate", or "test").

    Returns:
        DataTrace containing sampled batch and corresponding environments.

    Raises:
        ValueError: If split is invalid or datamodule not set up.
    """
    if split not in {"train", "validate", "test"}:
        raise ValueError(f"Invalid split '{split}'; must be 'train', 'validate', or 'test'")

    # Get the appropriate dataset
    if split == "train":
        dataset = datamodule.dataset
    elif split == "validate":
        dataset = datamodule.val_dataset
    else:  # test
        dataset = datamodule.test_dataset

    if dataset is None:
        raise ValueError(f"Datamodule not set up for split '{split}'. Call datamodule.setup() first.")

    # Sample a batch
    walk, visited = datamodule.sample_batch(split)

    # Assemble DataTrace
    return DataTrace(
        worlds=dataset.environments,
        walks=dataset.walks,
        visited=visited,
        meta={"split": split},
    )
