"""
Temporal Sequence Datasets

This module provides dataset classes for generating and working with temporal
observation sequences. These datasets are designed to test and demonstrate
the multi-scale temporal processing capabilities of TEM models.
"""

import math
from typing import List

import numpy as np
import torch
import torch.nn.functional as F
from torch import Tensor
from torch.utils.data import Dataset


class MultiScaleSequenceDataset(Dataset):
    """Dataset of temporal observation sequences with multi-scale dynamics.

    Generates sequences with temporal structure at multiple time scales:
    1. **Slow trends** (captured by low-frequency filters)
    2. **Medium oscillations** (captured by mid-frequency filters)
    3. **Fast changes** (captured by high-frequency filters)

    This dataset is useful for:
    - Testing multi-scale temporal filtering capabilities
    - Training sensory processors to capture patterns at different time scales
    - Evaluating representation learning in temporal domains

    The sequences are generated by combining sinusoidal components with
    different frequencies, then mapping the resulting signal to discrete
    observation indices.

    Args:
        n_sequences: Number of sequences to generate
        sequence_length: Length of each sequence (number of time steps)
        n_observations: Number of distinct observations (vocabulary size)
        seed: Random seed for reproducibility

    Example:
        >>> dataset = MultiScaleSequenceDataset(
        ...     n_sequences=1000,
        ...     sequence_length=50,
        ...     n_observations=45,
        ...     seed=42
        ... )
        >>> sequence = dataset[0]  # [seq_len, n_obs] one-hot tensor
        >>> sequence.shape
        torch.Size([50, 45])

    Note:
        All sequences are pre-generated during initialization for efficiency.
        This trades memory for speed, which is appropriate for moderate-sized
        datasets.
    """

    def __init__(
        self,
        n_sequences: int,
        sequence_length: int,
        n_observations: int,
        seed: int = 42,
    ):
        """Initialize dataset and pre-generate all sequences.

        Args:
            n_sequences: Number of sequences to generate
            sequence_length: Length of each sequence (number of time steps)
            n_observations: Number of distinct observations (vocabulary size)
            seed: Random seed for reproducibility
        """
        torch.manual_seed(seed)
        np.random.seed(seed)

        self.n_sequences = n_sequences
        self.sequence_length = sequence_length
        self.n_observations = n_observations

        # Pre-generate all sequences
        self.sequences = self._generate_sequences()

    def _generate_sequences(self) -> List[Tensor]:
        """Generate sequences with multi-scale temporal structure.

        Creates sequences by combining three sinusoidal components:
        - Slow: low-frequency sine wave (0.5 cycles over sequence)
        - Medium: mid-frequency sine wave (3 cycles over sequence)
        - Fast: high-frequency sine wave (10 cycles over sequence)

        The combined signal is normalized to [0, 1] and mapped to discrete
        observation indices, then converted to one-hot encoding.

        Returns:
            List of one-hot encoded sequences, each of shape [seq_len, n_obs]
        """
        sequences = []

        for _ in range(self.n_sequences):
            # Create time vector spanning multiple periods
            t = torch.linspace(0, 4 * math.pi, self.sequence_length)

            # Slow trend (low frequency - 0.5 cycles over 4π)
            slow = torch.sin(0.5 * t)

            # Medium oscillation (mid frequency - 3 cycles over 4π)
            medium = torch.sin(3 * t)

            # Fast changes (high frequency - 10 cycles over 4π, reduced amplitude)
            fast = torch.sin(10 * t) * 0.3

            # Combine components with different weights
            signal = slow + 0.5 * medium + fast

            # Normalize to [0, 1] range
            signal = (signal - signal.min()) / (signal.max() - signal.min())

            # Map to observation indices
            obs_indices = (signal * (self.n_observations - 1)).long()

            # Convert to one-hot encoding
            one_hot = F.one_hot(obs_indices, num_classes=self.n_observations).float()
            sequences.append(one_hot)

        return sequences

    def __len__(self) -> int:
        """Return the number of sequences in the dataset.

        Returns:
            Number of sequences
        """
        return self.n_sequences

    def __getitem__(self, idx: int) -> Tensor:
        """Get a sequence by index.

        Args:
            idx: Sequence index (0 to n_sequences-1)

        Returns:
            One-hot encoded sequence of shape [seq_len, n_obs]
        """
        return self.sequences[idx]
