"""Visualization utilities for pattern generation.

This module provides plotting functions for visualizing synthetic neural patterns
generated by the pattern generators in torch_tem.data.patterns:
- Place cell activity patterns and sparsity
- Grid cell activity patterns across frequencies
- Temporal evolution and smoothness
- Pattern correlations and relationships
"""

from typing import List, Tuple

import matplotlib.pyplot as plt
import numpy as np
import torch
from matplotlib.figure import Figure
from torch import Tensor

from ..types import AbstractLocation, Vector


def plot_place_cell_patterns(
    patterns: Vector,
    title: str = "Place Cell Activity Patterns",
    n_samples: int = 4,
) -> Figure:
    """Visualize place cell activity patterns.

    Creates a visualization showing:
    - Individual pattern activations (heatmap)
    - Sparsity distribution
    - Activation statistics

    Args:
        patterns: [B, n_p] place cell patterns
        title: Plot title
        n_samples: Number of sample patterns to show

    Returns:
        Figure with place cell visualizations
    """
    patterns_np = patterns.detach().cpu().numpy()
    batch_size, n_p = patterns_np.shape
    n_samples = min(n_samples, batch_size)

    fig, axes = plt.subplots(2, 2, figsize=(12, 10))
    fig.suptitle(title, fontsize=14, fontweight="bold")

    # Pattern heatmap
    ax = axes[0, 0]
    im = ax.imshow(patterns_np[:n_samples], aspect="auto", cmap="viridis", interpolation="none")
    ax.set_xlabel("Place Cell Index")
    ax.set_ylabel("Pattern Index")
    ax.set_title(f"Activity Patterns (first {n_samples} samples)")
    plt.colorbar(im, ax=ax, label="Activation")

    # Sparsity distribution
    ax = axes[0, 1]
    threshold = 0.01
    sparsity = (patterns_np > threshold).mean(axis=1)
    ax.hist(sparsity, bins=20, edgecolor="black", alpha=0.7)
    ax.axvline(sparsity.mean(), color="red", linestyle="--", linewidth=2, label=f"Mean: {sparsity.mean():.2%}")
    ax.set_xlabel("Active Fraction (> 0.01)")
    ax.set_ylabel("Count")
    ax.set_title("Sparsity Distribution")
    ax.legend()

    # Mean activation profile
    ax = axes[1, 0]
    mean_pattern = patterns_np.mean(axis=0)
    std_pattern = patterns_np.std(axis=0)
    ax.plot(mean_pattern, label="Mean", linewidth=2)
    ax.fill_between(range(n_p), mean_pattern - std_pattern, mean_pattern + std_pattern, alpha=0.3, label="±1 std")
    ax.set_xlabel("Place Cell Index")
    ax.set_ylabel("Activation")
    ax.set_title("Mean Activation Profile")
    ax.legend()
    ax.grid(True, alpha=0.3)

    # Statistics summary
    ax = axes[1, 1]
    ax.axis("off")
    stats_text = f"""Pattern Statistics:
    
    Batch Size: {batch_size}
    Dimensions: {n_p}
    
    Activation:
      Mean: {patterns_np.mean():.6f}
      Std: {patterns_np.std():.6f}
      Max: {patterns_np.max():.6f}
    
    Sparsity (>0.01):
      Mean: {sparsity.mean():.2%}
      Std: {sparsity.std():.2%}
    
    Active Cells:
      Mean: {(patterns_np > threshold).sum(axis=1).mean():.1f}
      Max: {(patterns_np > threshold).sum(axis=1).max():.0f}
    """
    ax.text(0.1, 0.5, stats_text, fontsize=11, verticalalignment="center", family="monospace")

    plt.tight_layout()
    return fig


def plot_grid_cell_patterns(
    patterns: AbstractLocation,
    frequencies: List[float],
    title: str = "Grid Cell Activity Patterns",
    n_samples: int = 4,
) -> Figure:
    """Visualize grid cell patterns across frequencies.

    Args:
        patterns: List of [B, n_g[f]] tensors for each frequency
        frequencies: List of frequency values
        title: Plot title
        n_samples: Number of sample patterns to show per frequency

    Returns:
        Figure with grid cell visualizations
    """
    n_f = len(patterns)
    patterns_np = [p.detach().cpu().numpy() for p in patterns]
    batch_size = patterns_np[0].shape[0]
    n_samples = min(n_samples, batch_size)

    fig, axes = plt.subplots(n_f, 3, figsize=(15, 4 * n_f))
    if n_f == 1:
        axes = axes.reshape(1, -1)
    fig.suptitle(title, fontsize=14, fontweight="bold")

    for f in range(n_f):
        pattern_f = patterns_np[f]
        n_g_f = pattern_f.shape[1]

        # Pattern heatmap
        ax = axes[f, 0]
        im = ax.imshow(pattern_f[:n_samples], aspect="auto", cmap="viridis", interpolation="none")
        ax.set_xlabel("Grid Cell Index")
        ax.set_ylabel("Pattern Index")
        ax.set_title(f"Frequency {f} (f={frequencies[f]:.2f}): {n_g_f} cells")
        plt.colorbar(im, ax=ax, label="Activation")

        # Mean activation profile
        ax = axes[f, 1]
        mean_pattern = pattern_f.mean(axis=0)
        std_pattern = pattern_f.std(axis=0)
        ax.plot(mean_pattern, label="Mean", linewidth=2)
        ax.fill_between(range(n_g_f), mean_pattern - std_pattern, mean_pattern + std_pattern, alpha=0.3, label="±1 std")
        ax.set_xlabel("Grid Cell Index")
        ax.set_ylabel("Activation")
        ax.set_title("Mean Profile")
        ax.legend()
        ax.grid(True, alpha=0.3)

        # Distribution
        ax = axes[f, 2]
        ax.hist(pattern_f.flatten(), bins=30, edgecolor="black", alpha=0.7)
        ax.axvline(pattern_f.mean(), color="red", linestyle="--", linewidth=2, label=f"Mean: {pattern_f.mean():.4f}")
        ax.set_xlabel("Activation Value")
        ax.set_ylabel("Count")
        ax.set_title("Activation Distribution")
        ax.legend()

    plt.tight_layout()
    return fig


def plot_temporal_patterns(
    sequences: Vector,
    title: str = "Temporal Pattern Evolution",
    n_cells_display: int = 50,
) -> Figure:
    """Visualize temporal evolution of patterns.

    Args:
        sequences: [T, B, n_cells] temporal sequences
        title: Plot title
        n_cells_display: Number of cells to display in heatmap

    Returns:
        Figure with temporal visualizations
    """
    sequences_np = sequences.detach().cpu().numpy()
    n_steps, batch_size, n_cells = sequences_np.shape
    n_cells_display = min(n_cells_display, n_cells)

    fig, axes = plt.subplots(2, 2, figsize=(14, 10))
    fig.suptitle(title, fontsize=14, fontweight="bold")

    # Temporal heatmap (first batch item)
    ax = axes[0, 0]
    im = ax.imshow(sequences_np[:, 0, :n_cells_display].T, aspect="auto", cmap="viridis", interpolation="none")
    ax.set_xlabel("Time Step")
    ax.set_ylabel(f"Cell Index (first {n_cells_display})")
    ax.set_title("Activity Over Time (Batch 0)")
    plt.colorbar(im, ax=ax, label="Activation")

    # Temporal smoothness
    ax = axes[0, 1]
    diffs = np.linalg.norm(np.diff(sequences_np, axis=0), axis=2)  # [T-1, B]
    mean_diff = diffs.mean(axis=1)
    std_diff = diffs.std(axis=1)
    ax.plot(mean_diff, label="Mean difference", linewidth=2)
    ax.fill_between(range(len(mean_diff)), mean_diff - std_diff, mean_diff + std_diff, alpha=0.3, label="±1 std")
    ax.set_xlabel("Time Step")
    ax.set_ylabel("Pattern Difference (L2 norm)")
    ax.set_title("Temporal Smoothness")
    ax.legend()
    ax.grid(True, alpha=0.3)

    # Mean activity over time
    ax = axes[1, 0]
    mean_activity = sequences_np.mean(axis=2)  # [T, B]
    for b in range(min(3, batch_size)):
        ax.plot(mean_activity[:, b], label=f"Batch {b}", alpha=0.7)
    ax.set_xlabel("Time Step")
    ax.set_ylabel("Mean Activation")
    ax.set_title("Mean Activity Evolution")
    ax.legend()
    ax.grid(True, alpha=0.3)

    # Statistics
    ax = axes[1, 1]
    ax.axis("off")
    avg_diff = diffs.mean()
    stats_text = f"""Temporal Statistics:
    
    Sequence Length: {n_steps}
    Batch Size: {batch_size}
    Dimensions: {n_cells}
    
    Activation:
      Mean: {sequences_np.mean():.6f}
      Std: {sequences_np.std():.6f}
    
    Temporal Smoothness:
      Avg Difference: {avg_diff:.4f}
      Min Difference: {diffs.min():.4f}
      Max Difference: {diffs.max():.4f}
    
    Autocorrelation (lag 1):
      Mean: {np.corrcoef(sequences_np[:-1, 0, :].flatten(), sequences_np[1:, 0, :].flatten())[0, 1]:.4f}
    """
    ax.text(0.1, 0.5, stats_text, fontsize=11, verticalalignment="center", family="monospace")

    plt.tight_layout()
    return fig


def plot_oscillatory_patterns(
    g_history: List[AbstractLocation],
    frequencies: List[float],
    title: str = "Oscillatory Grid Cell Patterns",
    cell_indices: List[int] = None,
) -> Figure:
    """Visualize oscillatory grid cell patterns.

    Args:
        g_history: List of T timesteps, each with n_f tensors [B, n_g[f]]
        frequencies: List of frequency values
        title: Plot title
        cell_indices: Indices of cells to display per frequency (if None, shows first 3)

    Returns:
        Figure with oscillatory pattern visualizations
    """
    n_steps = len(g_history)
    n_f = len(g_history[0])
    batch_idx = 0  # Show first batch item

    # Extract traces
    traces = []
    for f in range(n_f):
        g_f_trace = torch.stack([g_history[t][f] for t in range(n_steps)])  # [T, B, n_g[f]]
        traces.append(g_f_trace[:, batch_idx, :].detach().cpu().numpy())  # [T, n_g[f]]

    if cell_indices is None:
        cell_indices = [0, 1, 2]

    fig, axes = plt.subplots(n_f, 2, figsize=(14, 4 * n_f))
    if n_f == 1:
        axes = axes.reshape(1, -1)
    fig.suptitle(title, fontsize=14, fontweight="bold")

    for f in range(n_f):
        trace_f = traces[f]  # [T, n_g[f]]
        n_g_f = trace_f.shape[1]

        # Time series of individual cells
        ax = axes[f, 0]
        for cell_idx in cell_indices:
            if cell_idx < n_g_f:
                ax.plot(trace_f[:, cell_idx], label=f"Cell {cell_idx}", alpha=0.8)
        ax.set_xlabel("Time Step")
        ax.set_ylabel("Activation")
        ax.set_title(f"Frequency {f} (f={frequencies[f]:.2f}): Individual Cells")
        ax.legend()
        ax.grid(True, alpha=0.3)

        # Heatmap of all cells over time
        ax = axes[f, 1]
        im = ax.imshow(trace_f.T, aspect="auto", cmap="RdBu_r", interpolation="none")
        ax.set_xlabel("Time Step")
        ax.set_ylabel("Cell Index")
        ax.set_title(f"All {n_g_f} Cells Over Time")
        plt.colorbar(im, ax=ax, label="Activation")

    plt.tight_layout()
    return fig


def plot_pattern_correlations(
    g_patterns: AbstractLocation,
    p_patterns: Vector,
    frequencies: List[float],
    title: str = "Grid-Place Pattern Correlations",
) -> Figure:
    """Visualize correlations between grid and place cell patterns.

    Args:
        g_patterns: List of [B, n_g[f]] grid patterns
        p_patterns: [B, n_p] place patterns
        frequencies: List of frequency values
        title: Plot title

    Returns:
        Figure showing pattern correlations
    """
    n_f = len(g_patterns)
    g_flat = torch.cat(g_patterns, dim=1).detach().cpu().numpy()  # [B, sum(n_g)]
    p_np = p_patterns.detach().cpu().numpy()  # [B, n_p]

    fig, axes = plt.subplots(1, 3, figsize=(15, 5))
    fig.suptitle(title, fontsize=14, fontweight="bold")

    # Grid pattern correlations
    ax = axes[0]
    g_corr = np.corrcoef(g_flat.T)
    im = ax.imshow(g_corr, cmap="RdBu_r", vmin=-1, vmax=1, interpolation="none")
    ax.set_xlabel("Grid Cell Index")
    ax.set_ylabel("Grid Cell Index")
    ax.set_title(f"Grid Cell Correlations\n({g_flat.shape[1]} cells)")
    plt.colorbar(im, ax=ax, label="Correlation")

    # Place pattern correlations
    ax = axes[1]
    p_corr = np.corrcoef(p_np.T)
    im = ax.imshow(p_corr, cmap="RdBu_r", vmin=-1, vmax=1, interpolation="none")
    ax.set_xlabel("Place Cell Index")
    ax.set_ylabel("Place Cell Index")
    ax.set_title(f"Place Cell Correlations\n({p_np.shape[1]} cells)")
    plt.colorbar(im, ax=ax, label="Correlation")

    # Cross-correlation (grid vs place)
    ax = axes[2]
    # Compute correlation between each grid and place cell
    cross_corr = np.corrcoef(g_flat.T, p_np.T)[: g_flat.shape[1], g_flat.shape[1] :]
    im = ax.imshow(cross_corr, cmap="RdBu_r", vmin=-1, vmax=1, aspect="auto", interpolation="none")
    ax.set_xlabel("Place Cell Index")
    ax.set_ylabel("Grid Cell Index")
    ax.set_title("Grid-Place Cross-Correlations")
    plt.colorbar(im, ax=ax, label="Correlation")

    plt.tight_layout()
    return fig


def plot_pattern_comparison(
    patterns_dict: dict,
    title: str = "Pattern Generator Comparison",
    n_samples: int = 3,
) -> Figure:
    """Compare patterns from different generators.

    Args:
        patterns_dict: Dictionary mapping generator names to [B, n_cells] patterns
        title: Plot title
        n_samples: Number of samples to show per generator

    Returns:
        Figure comparing different pattern types
    """
    n_generators = len(patterns_dict)
    fig, axes = plt.subplots(n_generators, 2, figsize=(12, 4 * n_generators))
    if n_generators == 1:
        axes = axes.reshape(1, -1)
    fig.suptitle(title, fontsize=14, fontweight="bold")

    for i, (name, patterns) in enumerate(patterns_dict.items()):
        patterns_np = patterns.detach().cpu().numpy()
        batch_size, n_cells = patterns_np.shape
        n_samples_actual = min(n_samples, batch_size)

        # Heatmap
        ax = axes[i, 0]
        im = ax.imshow(patterns_np[:n_samples_actual], aspect="auto", cmap="viridis", interpolation="none")
        ax.set_xlabel("Cell Index")
        ax.set_ylabel("Pattern Index")
        ax.set_title(f"{name}: {n_cells} cells")
        plt.colorbar(im, ax=ax, label="Activation")

        # Distribution
        ax = axes[i, 1]
        ax.hist(patterns_np.flatten(), bins=30, edgecolor="black", alpha=0.7)
        ax.axvline(patterns_np.mean(), color="red", linestyle="--", linewidth=2, label=f"Mean: {patterns_np.mean():.4f}")
        ax.set_xlabel("Activation Value")
        ax.set_ylabel("Count")
        ax.set_title(f"{name}: Distribution")
        ax.legend()

    plt.tight_layout()
    return fig
